pipeline{
    agent any
    environment {
        PATH = "$PATH:C:/Program Files/apache-maven-3.8.8/bin"
    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://github.com/cloudtraineer/maven_app_deploy.git'
            }
         }        
       stage('Build'){
            steps{
                sh 'mvn clean package'
            }
         }
        stage('SonarQube analysis') {
        	steps{
        		withSonarQubeEnv('sonarqube7.9.6') { 
        			sh "${scannerHome}/bin/sonar-scanner"
        			sh "mvn sonar:sonar"
    }
        }
        }
       
    }
}
